name: Deploy app
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    needs: build
    runs-on: deploy-server
    steps:
      - uses: actions/checkout@v3
      - name: Setup app
        run: |
          
          